import fs from "fs";
import path from "path";
import matter from "gray-matter";
import Head from "next/head";
import Author from "../components/Author";
import styles from "../styles/Home/Home.module.css";
import Post from "../components/Post";
import { sortByDate } from "../utils/date";

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>CodeMacaw</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <Author />
        <div className={styles.posts}>
          {posts?.map((post, index) => {
            return <Post post={post} key={index} />;
          })}
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  // Get files from the posts dir
  const files = fs.readdirSync(path.join("posts"));

  // Get slug and frontmatter from posts
  const posts = files.map((filename) => {
    // Create slug
    const slug = filename.replace(".md", "");

    // Get frontmatter
    const markdownWithMeta = fs.readFileSync(
      path.join("posts", filename),
      "utf-8"
    );

    const { data: frontmatter } = matter(markdownWithMeta);

    return {
      slug,
      frontmatter,
    };
  });

  return {
    props: {
      posts: posts.sort(sortByDate),
    },
  };
}
